Repository Konkuk-KUIT/KUIT6_WEB-Frontend, pull requests merged in 2025-09, with the labels that each got.

#5 [1주차] 자기소개 HTML
  week1/JeongYuna/index.html
  week1/JeongYuna/me.png
Labels: 정윤아

#12 [1주차] 자기소개 HTML
  week1/MoonSeoIn/index.html
  week1/MoonSeoIn/seoin.jpeg
Labels: 문서인

#13 [1주차] 자기소개 HTML
  week1/LeeHyeonSeung/hs_profileimage.jpg
  week1/LeeHyeonSeung/index.html
Labels: 이현승

#14 [1주차] 자기소개 HTML
  week1/Sehyun/index.html
Labels: 조세현

#16 [1주차] 자기소개 HTML
  week1/Leeyeseul/index.html
Labels: 이예슬

#17 [1주차] 자기소개 HTML
  week1/ChoiSeungYeon/MIRO.png
  week1/ChoiSeungYeon/index.html
Labels: 최승연

#19 [1주차] 자기소개 HTML
  week1/Choeunseo/index.html
Labels: 조은서

#20 [1주차] 자기소개 HTML
  week1/ShinBoYeon/index.html
Labels: 신보연

#18 [1주차] 자기소개 HTML
  week1/KimDoeun/index.html
  week1/KimDoeun/profile.jpg
Labels: 김도은

#15 [1주차] 자기소개 HTML
  week1/KimNaYeon/index.html
  week1/KimNaYeon/profileImage.png
Labels: 김나연

#10 [1주차] 자기 소개 HTML
  week1/JangSeoyun/index.html
Labels: 장서윤

#29 [2주차] 당근마켓 화면 구현
  week2/JungSangHyun/assets/bill.svg
  week2/JungSangHyun/assets/chat.svg
  week2/JungSangHyun/assets/home.svg
  week2/JungSangHyun/assets/like.svg
  week2/JungSangHyun/assets/news.svg
  week2/JungSangHyun/assets/place_marker.svg
  week2/JungSangHyun/assets/right.svg
  week2/JungSangHyun/assets/setting.svg
  week2/JungSangHyun/assets/shopping_bag.svg
  week2/JungSangHyun/assets/user.svg
  week2/JungSangHyun/index.css
  week2/JungSangHyun/index.html
  week2/JungSangHyun/reset.css
Labels: 정상현

#30 [2주차] 당근마켓 화면 구현
  week2/moonseoin/assets/chat.svg
  week2/moonseoin/assets/chevron-right.svg
  week2/moonseoin/assets/document.svg
  week2/moonseoin/assets/heart.svg
  week2/moonseoin/assets/home.svg
  week2/moonseoin/assets/location.svg
  week2/moonseoin/assets/news.svg
  week2/moonseoin/assets/profile.svg
  week2/moonseoin/assets/setting.svg
  week2/moonseoin/assets/shopping-bag.svg
  week2/moonseoin/index.css
  week2/moonseoin/index.html
  week2/moonseoin/reset.css
Labels: 문서인

#32 [2주차] 당근마켓 화면 구현
  week2/KimNaYeon/assets/arrow.svg
  week2/KimNaYeon/assets/chatting.svg
  week2/KimNaYeon/assets/heart.svg
  week2/KimNaYeon/assets/home.svg
  week2/KimNaYeon/assets/list.svg
  week2/KimNaYeon/assets/location.svg
  week2/KimNaYeon/assets/my.svg
  week2/KimNaYeon/assets/news.svg
  week2/KimNaYeon/assets/profile.svg
  week2/KimNaYeon/assets/setting.svg
  week2/KimNaYeon/assets/shopping.svg
  week2/KimNaYeon/index.css
  week2/KimNaYeon/index.html
  week2/KimNaYeon/reset.css
Labels: 김나연

#33 [2주차] 당근마켓 화면 구현
  week2/KimJiHyun/assets/chat.svg
  week2/KimJiHyun/assets/heart.svg
  week2/KimJiHyun/assets/home.svg
  week2/KimJiHyun/assets/list.svg
  week2/KimJiHyun/assets/map.svg
  week2/KimJiHyun/assets/me.svg
  week2/KimJiHyun/assets/news.svg
  week2/KimJiHyun/assets/setting.svg
  week2/KimJiHyun/assets/shopping_bag.svg
  week2/KimJiHyun/assets/user-profile.svg
  week2/KimJiHyun/assets/user-profile_more.svg
  week2/KimJiHyun/index.css
  week2/KimJiHyun/index.html
  week2/KimJiHyun/reset.css
Labels: 김지현

#34 [2주차] 당근마켓 화면 구현
  week2/Chosehyun/assets/bag.svg
  week2/Chosehyun/assets/bill.svg
  week2/Chosehyun/assets/chat.svg
  week2/Chosehyun/assets/forward.svg
  week2/Chosehyun/assets/heart.svg
  week2/Chosehyun/assets/home.svg
  week2/Chosehyun/assets/news.svg
  week2/Chosehyun/assets/ping.svg
  week2/Chosehyun/assets/profile.svg
  week2/Chosehyun/assets/profilephoto.svg
  week2/Chosehyun/assets/setting.svg
  week2/Chosehyun/index.css
  week2/Chosehyun/index.html
  week2/Chosehyun/reset.css
Labels: 조세현

#38 [2주차] 당근마켓 화면 구현
  week2/ShinBoYeon/assets/buy.svg
  week2/ShinBoYeon/assets/chatting.svg
  week2/ShinBoYeon/assets/doc.svg
  week2/ShinBoYeon/assets/forward.svg
  week2/ShinBoYeon/assets/home.svg
  week2/ShinBoYeon/assets/interest.svg
  week2/ShinBoYeon/assets/locallife.svg
  week2/ShinBoYeon/assets/location.svg
  week2/ShinBoYeon/assets/mycarrot.svg
  week2/ShinBoYeon/assets/profile.svg
  week2/ShinBoYeon/assets/sell.svg
  week2/ShinBoYeon/assets/setting.svg
  week2/ShinBoYeon/index.css
  week2/ShinBoYeon/index.html
  week2/ShinBoYeon/reset.css
Labels: 신보연

#39 [2주차] 당근마켓 화면 구현
  week2/ChoiSeungYeon/assets/Bill.svg
  week2/ChoiSeungYeon/assets/Chat.svg
  week2/ChoiSeungYeon/assets/Forward.svg
  week2/ChoiSeungYeon/assets/Frame 51.svg
  week2/ChoiSeungYeon/assets/Heart.svg
  week2/ChoiSeungYeon/assets/Home.svg
  week2/ChoiSeungYeon/assets/News.svg
  week2/ChoiSeungYeon/assets/Place Marker.svg
  week2/ChoiSeungYeon/assets/Settings.svg
  week2/ChoiSeungYeon/assets/Shopping Bag.svg
  week2/ChoiSeungYeon/assets/User.svg
  week2/ChoiSeungYeon/index.css
  week2/ChoiSeungYeon/index.html
  week2/ChoiSeungYeon/reset.css
Labels: 최승연

#31 [2주차] 당근마켓 화면 구현
  week2/KimDongHa/assets/Bill.png
  week2/KimDongHa/assets/Chat.png
  week2/KimDongHa/assets/Forward.png
  week2/KimDongHa/assets/Frame .svg
  week2/KimDongHa/assets/Frame 5.svg
  week2/KimDongHa/assets/Frame 51.svg
  week2/KimDongHa/assets/Frame 52.svg
  week2/KimDongHa/assets/Heart.png
  week2/KimDongHa/assets/Home.svg
  week2/KimDongHa/assets/News.svg
  week2/KimDongHa/assets/Place Marker.png
  week2/KimDongHa/assets/Settings.svg
  week2/KimDongHa/assets/Shopping Bag.png
  week2/KimDongHa/assets/User.png
  week2/KimDongHa/index.css
  week2/KimDongHa/index.html
  week2/KimDongHa/reset.css
Labels: 김동하

#40 [2주차] 당근마켓 화면 구현
  .DS_Store
  week2/.DS_Store
  week2/baikhyunjun/assets/Chat.png
  week2/baikhyunjun/assets/Forward.png
  week2/baikhyunjun/assets/Home.png
  week2/baikhyunjun/assets/Mask group 2.png
  week2/baikhyunjun/assets/Mask group-1.png
  week2/baikhyunjun/assets/Mask group.png
  week2/baikhyunjun/assets/News.png
  week2/baikhyunjun/assets/Place Marker.png
  week2/baikhyunjun/assets/User.png
  week2/baikhyunjun/assets/Vector-2.png
  week2/baikhyunjun/assets/Vector.png
  week2/baikhyunjun/index.css
  week2/baikhyunjun/index.html
Labels: 백현준

#23 [2주차] 당근마켓 화면 구현
  week2/.DS_Store
  week2/seoyunJang/.DS_Store
  week2/seoyunJang/assets/activity.svg
  week2/seoyunJang/assets/around.svg
  week2/seoyunJang/assets/buy.svg
  week2/seoyunJang/assets/chat.svg
  week2/seoyunJang/assets/forward.svg
  week2/seoyunJang/assets/home.svg
  week2/seoyunJang/assets/like.svg
  week2/seoyunJang/assets/my.svg
  week2/seoyunJang/assets/sell.svg
  week2/seoyunJang/assets/settting.svg
  week2/seoyunJang/index.css
  week2/seoyunJang/index.html
  week2/seoyunJang/reset.css
Labels: 장서윤
