Repository Konkuk-KUIT/KUIT6_WEB-Frontend, pull requests merged in 2025-10, with the labels that each got.

#41 [3주차] TodoList 만들기
  week3/LimChaeeun/index.css
  week3/LimChaeeun/index.html
  week3/LimChaeeun/index.js
Labels: 임채은

#46 [3주차] TodoList 만들기
  week3/LeeHyeonSeung/index.css
  week3/LeeHyeonSeung/index.html
  week3/LeeHyeonSeung/index.js
Labels: 이현승

#47 [3주차] TodoList 만들기
  week3/moonseoin/index.css
  week3/moonseoin/index.html
  week3/moonseoin/index.js
Labels: 문서인

#55 [3주차] TodoList 만들기
  week3/JeongYuna/index.css
  week3/JeongYuna/index.html
  week3/JeongYuna/index.js
Labels: 정윤아, 3조

#57 [3주차] TodoList 만들기
  week3/JungSangHyun/index.css
  week3/JungSangHyun/index.html
  week3/JungSangHyun/index.js
Labels: 정상현

#56 [3주차] TodoList 만들기
  week2/ShinBoYeon/index.css
  week3/ShinBoYeon/index.css
  week3/ShinBoYeon/index.html
  week3/ShinBoYeon/index.js
Labels: 신보연, 2조

#53 [3주차] TodoList 만들기
  week3/Leeyeseul/index.css
  week3/Leeyeseul/index.html
  week3/Leeyeseul/index.js
Labels: 이예슬, 4조
